name: 'Extract Event Text'
description: 'GitHubイベントタイプに応じてテキストを抽出'
outputs:
  text:
    description: '抽出されたイベントテキスト'
    value: ${{ steps.extract.outputs.text }}
runs:
  using: 'composite'
  steps:
    - name: Extract event-specific text
      id: extract
      shell: bash
      env:
        EVENT_NAME: ${{ github.event_name }}
        COMMENT_BODY: ${{ github.event.comment.body }}
        REVIEW_BODY: ${{ github.event.review.body }}
        ISSUE_BODY: ${{ github.event.issue.body }}
        ISSUE_TITLE: ${{ github.event.issue.title }}
      run: |
        # AI: 環境変数経由でテキストを取得（GitHubが自動的にエスケープ処理）
        if [ "$EVENT_NAME" = "issue_comment" ]; then
          EVENT_TEXT="$COMMENT_BODY"
        elif [ "$EVENT_NAME" = "pull_request_review_comment" ]; then
          EVENT_TEXT="$COMMENT_BODY"
        elif [ "$EVENT_NAME" = "pull_request_review" ]; then
          EVENT_TEXT="$REVIEW_BODY"
        elif [ "$EVENT_NAME" = "issues" ]; then
          # AI: issueの場合はbodyとtitleの両方をチェック
          if [ -n "$ISSUE_BODY" ]; then
            EVENT_TEXT="$ISSUE_BODY"
          else
            EVENT_TEXT="$ISSUE_TITLE"
          fi
        fi

        # AI: 複数行テキストを正しく出力するためにheredocを使用
        echo "text<<EOF" >> $GITHUB_OUTPUT
        echo "$EVENT_TEXT" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
