name: 'Check Claude Setup Needed'
description: 'Claude Codeを使用してセットアップが必要かどうかを判定'

inputs:
  claude_code_oauth_token:
    description: 'Claude Code OAuth トークン'
    required: true
  event_text:
    description: '分析対象のイベントテキスト（未入力の場合は自動抽出）'
    required: false
    default: ''

outputs:
  needs_setup:
    description: 'セットアップが必要かどうか（true/false）'
    value: ${{ steps.parse-setup-result.outputs.needs_setup }}

runs:
  using: 'composite'
  steps:
    - name: Extract event text if not provided
      id: extract-event-text
      if: ${{ inputs.event_text == '' }}
      uses: ./extract-event-text
      
    - name: Check if setup is needed
      id: setup-check
      uses: anthropics/claude-code-base-action@beta
      with:
        claude_code_oauth_token: ${{ inputs.claude_code_oauth_token }}
        prompt: |
          以下のユーザーからの依頼内容を分析して、開発環境のセットアップが必要かどうかを判定してください。

          依頼内容:
          ${{ inputs.event_text || steps.extract-event-text.outputs.text }}

          **まず以下の開発作業を示すキーワードをチェックしてください:**
          - 「実装を進めて」「実装して」「開発を進めて」「開発して」
          - 「修正を進めて」「修正して」「レビュー内容に対応して」
          - 「作成して」「追加して」「更新して」「変更して」「削除して」
          - 「リファクタリングして」「デプロイして」「ビルドして」「テストして」

          **次に以下のいずれかの作業を含む可能性があるかを判定してください:**
          - コードの修正・追加・削除
          - テストの実行・作成
          - データベース操作・マイグレーション
          - ビルド・デプロイの実行
          - 依存関係のインストール・更新
          - 設定ファイルの変更
          - 静的解析・リンターの実行

          **判定指針:**
          - 上記キーワードが含まれている場合は「SETUP_NEEDED」
          - 明確な開発作業の指示がある場合は「SETUP_NEEDED」
          - 疑わしい場合や曖昧な場合は安全側に倒して「SETUP_NEEDED」
          - 単純な質問や説明のみの場合は「SETUP_NOT_NEEDED」

          回答は「SETUP_NEEDED」または「SETUP_NOT_NEEDED」のみで答えてください。
        max_turns: 1
        timeout_minutes: 2

    - name: Parse setup check result
      id: parse-setup-result
      shell: bash
      run: |
        # AI: Claude Code の実行結果から判定結果を抽出
        EXECUTION_FILE="${{ steps.setup-check.outputs.execution_file }}"
        if [ -f "$EXECUTION_FILE" ]; then
          # AI: JSONから最後のresultオブジェクトを抽出してSETUP_NEEDEDが含まれているかチェック
          RESULT=$(cat "$EXECUTION_FILE" | jq -r '.[] | select(.type == "result") | .result' | tail -1)
          if echo "$RESULT" | grep -q "SETUP_NEEDED"; then
            echo "needs_setup=true" >> $GITHUB_OUTPUT
            echo "Setup is needed based on Claude's analysis"
          else
            echo "needs_setup=false" >> $GITHUB_OUTPUT
            echo "Setup is not needed based on Claude's analysis"
          fi
        else
          echo "needs_setup=false" >> $GITHUB_OUTPUT
          echo "Could not parse result, defaulting to no setup"
        fi
